# Metadata
site_name: Dragon RP
site_description: "The site that will help kickstart your role-play"
site_author: "Dragon Projects"

# Theming
theme:
  name: "material"
  favicon: assets/favicon.ico
  palette:
    primary: "red"
    accent: "red"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  logo:
    icon: "book"

# Extensions
markdown_extensions:
  - admonition
  - footnotes

# Import
extra_css:
  - "assets/style.css"
extra_javascript:
  - "assets/script.js"

# Repository
repo_url: "https://github.com/jelle619/dragonrp"
edit_uri: "edit/master/docs/"

# Copyright
copyright: "<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png"/></a>"
