backend:
  name: github
  repo: jelle619/dragonrp
  branch: master

logo_url: ../assets/logo.png
public_folder: "docs/"
media_folder: "docs/assets"
publish_mode: editorial_workflow

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "string"}
  - name: "extensions"
    label: "Extensions"
    folder: "docs/extensions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "string"}
