backend:
  name: github
  repo: jelle619/dragonrp

logo_url: ../assets/logo.png
public_folder: "docs/"
media_folder: "docs/assets"
publish_mode: editorial_workflow

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}
